const ERROR_CODES = {
  ILLEGAL_FUNCTION: 1,
  ILLEGAL_DATA_ADDRESS: 2,
  ILLEGAL_DATA_VALUE: 3,
  SERVER_DEVICE_FAILURE: 4,
  ACKNOWLEDGE: 5,
  SERVER_DEVICE_BUSY: 6,
  ___: 7,
  MEMORY_PARITY_ERROR: 8,
  GATEWAY_PATH_UNAVAILABLE: 10,
  GATEWAY_TARGET_DEVICE_FAILED_TO_RESPOND: 11,
};

const FUNCTION_CODES = {
  READ_COILS: 1,
  READ_DISCRETE_INPUTS: 2,
  READ_HOLDING_REGISTERS: 3,
  READ_INPUT_REGISTERS: 4,
  WRITE_SINGLE_COIL: 5,
  WRITE_SINGLE_REGISTER: 6,
  WRITE_MULTIPLE_COILS: 15,
  WRITE_HOLDING_REGISTERS: 16,
};

const REV_FUNCTION_CODES = {
  1: "READ_COILS",
  2: "READ_DISCRETE_INPUTS",
  3: "READ_HOLDING_REGISTERS",
  4: "READ_INPUT_REGISTERS",
  5: "WRITE_SINGLE_COIL",
  6: "WRITE_SINGLE_REGISTER",
  15: "WRITE_MULTIPLE_COILS",
  16: "WRITE_HOLDING_REGISTERS",
};

const FUNCTION_NAMES = {
  READ_COILS: "READ_COILS",
  READ_DISCRETE_INPUTS: "READ_DISCRETE_INPUTS",
  READ_HOLDING_REGISTERS: "READ_HOLDING_REGISTERS",
  READ_INPUT_REGISTERS: "READ_INPUT_REGISTERS",
  WRITE_SINGLE_COIL: "WRITE_SINGLE_COIL",
  WRITE_SINGLE_REGISTER: "WRITE_SINGLE_REGISTER",
  WRITE_MULTIPLE_COILS: "WRITE_MULTIPLE_COILS",
  WRITE_HOLDING_REGISTERS: "WRITE_HOLDING_REGISTERS",
};

module.exports = {
  ERROR_CODES,
  FUNCTION_CODES,
  FUNCTION_NAMES,
  REV_FUNCTION_CODES,
};
